plugins {
	id 'java-library'
	id 'maven-publish'
}

group = 'com.hia'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

def lombokVersion = '1.18.38'
def springVersion = '6.2.19'

dependencies {
	//spring-web
	api "org.springframework:spring-web:$springVersion"
	implementation "org.springframework:spring-context:$springVersion"

	// Lombok
	compileOnly "org.projectlombok:lombok:$lombokVersion"
	annotationProcessor "org.projectlombok:lombok:$lombokVersion"

	implementation 'org.slf4j:slf4j-api:2.0.17'

	testCompileOnly "org.projectlombok:lombok:$lombokVersion"
	testAnnotationProcessor "org.projectlombok:lombok:$lombokVersion"

	// Test
	testImplementation platform('org.junit:junit-bom:5.13.4')
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
