plugins {
	id 'java-library'
	id 'maven-publish'
}

group = 'com.hia'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

def lombokVersion = '1.18.38'
def springVersion = '6.2.19'

dependencies {
	//spring-web
	api "org.springframework:spring-web:$springVersion"
	implementation "org.springframework:spring-context:$springVersion"
	implementation 'jakarta.validation:jakarta.validation-api:3.1.1'
	compileOnly "org.springframework:spring-webmvc:$springVersion"

	compileOnly 'jakarta.servlet:jakarta.servlet-api:6.1.0'

	// Lombok
	compileOnly "org.projectlombok:lombok:$lombokVersion"
	annotationProcessor "org.projectlombok:lombok:$lombokVersion"

	implementation 'org.slf4j:slf4j-api:2.0.17'

	testCompileOnly "org.projectlombok:lombok:$lombokVersion"
	testAnnotationProcessor "org.projectlombok:lombok:$lombokVersion"

	// Test
	testImplementation platform('org.junit:junit-bom:5.13.4')
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.mockito:mockito-core:5.20.0'
	testImplementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'
	testImplementation "org.springframework:spring-webmvc:$springVersion"
}

tasks.named('test') {
	useJUnitPlatform()
}
